def get_storyboard():
    return [
        {"keyword": "measles", "identity_keyword": "North Carolina", "text": "A measles exposure has been reported in North Carolina, according to recent health reports.", "duration": 4, "visual_type": "emotion"},
        {"keyword": "exposure", "identity_keyword": "health reports", "text": "The North Carolina Department of Health and Human Services has confirmed that an individual with a measles infection was present in the state, potentially exposing others to the virus.", "duration": 5, "visual_type": "emotion"},
        {"keyword": "infection", "identity_keyword": "North Carolina Department of Health and Human Services", "text": "Health officials are working to identify and notify those who may have been in close contact with the infected person, and are advising individuals who may have been exposed to monitor for symptoms such as fever, cough, and rash.", "duration": 4, "visual_type": "identity"},
        {"keyword": "health officials", "identity_keyword": "infected person", "text": "The measles virus is highly contagious and can spread through the air when an infected person coughs or sneezes, and the state health department is taking steps to prevent further transmission and protect public health.", "duration": 5, "visual_type": "emotion"},
        {"keyword": "measles virus", "identity_keyword": "public health", "text": "A measles exposure has been reported in North Carolina, according to recent health reports.", "duration": 4, "visual_type": "emotion"},
        {"keyword": "contagious", "identity_keyword": "state health department", "text": "The North Carolina Department of Health and Human Services has confirmed that an individual with a measles infection was present in the state, potentially exposing others to the virus.", "duration": 4, "visual_type": "identity"},
        {"keyword": "transmission", "identity_keyword": "health officials", "text": "Health officials are working to identify and notify those who may have been in close contact with the infected person, and are advising individuals who may have been exposed to monitor for symptoms such as fever, cough, and rash.", "duration": 5, "visual_type": "emotion"},
        {"keyword": "symptoms", "identity_keyword": "infected person", "text": "The measles virus is highly contagious and can spread through the air when an infected person coughs or sneezes, and the state health department is taking steps to prevent further transmission and protect public health.", "duration": 4, "visual_type": "identity"},
        {"keyword": "fever", "identity_keyword": "public health", "text": "A measles exposure has been reported in North Carolina, according to recent health reports.", "duration": 4, "visual_type": "emotion"},
        {"keyword": "cough", "identity_keyword": "state health department", "text": "The North Carolina Department of Health and Human Services has confirmed that an individual with a measles infection was present in the state, potentially exposing others to the virus.", "duration": 4, "visual_type": "identity"},
        {"keyword": "rash", "identity_keyword": "health officials", "text": "Health officials are working to identify and notify those who may have been in close contact with the infected person, and are advising individuals who may have been exposed to monitor for symptoms such as fever, cough, and rash.", "duration": 5, "visual_type": "emotion"},
        {"keyword": "virus", "identity_keyword": "infected person", "text": "The measles virus is highly contagious and can spread through the air when an infected person coughs or sneezes, and the state health department is taking steps to prevent further transmission and protect public health.", "duration": 4, "visual_type": "identity"},
        {"keyword": "air", "identity_keyword": "public health", "text": "A measles exposure has been reported in North Carolina, according to recent health reports.", "duration": 4, "visual_type": "emotion"},
        {"keyword": "sneezes", "identity_keyword": "state health department", "text": "The North Carolina Department of Health and Human Services has confirmed that an individual with a measles infection was present in the state, potentially exposing others to the virus.", "duration": 4, "visual_type": "identity"}
    ]
